# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=5, help_text='How frequently sensors will be polled', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Relay', help_text='The name you will refer to this relay as. Must be unique. 24 characters', max_length=24, unique=True)),
                ('gpio', models.IntegerField(default=1, help_text='GPIO pin number', unique=True)),
                ('active', models.BooleanField(default=True, help_text='Device active or not')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sensor 1', help_text='The name you refer to this sensor as. Must be unique. 24 characters', max_length=24, unique=True)),
                ('sensor_type', models.CharField(choices=[('temp', 'Temperature'), ('temphumid', 'Temperature+Humidity'), ('moisture', 'Moisture'), ('light', 'Light')], default='temp', max_length=12)),
                ('device', models.CharField(blank=True, help_text='Device type/model info. 24 characters', max_length=24, null=True)),
                ('gpio', models.IntegerField(default=1, help_text='GPIO pin number', unique=True)),
                ('active', models.BooleanField(default=True, help_text='Device active or not')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
