# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 20:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('documentation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pollinterval',
            name='value',
            field=models.IntegerField(choices=[(5, '5 minutes'), (10, '10 minutes'), (15, '15 minutes'), (30, '30 minutes')], default=5, help_text='How frequently sensors will be polled', unique=True),
        ),
        migrations.AlterField(
            model_name='relay',
            name='active',
            field=models.BooleanField(default=True, help_text='Device active or not. Inactive relays will not be polled.'),
        ),
        migrations.AlterField(
            model_name='relay',
            name='gpio',
            field=models.IntegerField(default=1, help_text='GPIO pin number', unique=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='active',
            field=models.BooleanField(default=True, help_text='Device active or not. Inactive sensors will not be polled.'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='gpio',
            field=models.IntegerField(default=1, help_text='GPIO pin number', unique=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(0)]),
        ),
    ]
