# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 11:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20170804_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='WirelessOutlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Outlet 1', help_text='The name you will refer to this outlet as. Must be unique. 24 characters', max_length=24, unique=True)),
                ('active', models.BooleanField(default=True, help_text='Device active or not. Inactive relays will not be polled.')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WirelessTx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpio', models.IntegerField(default=1, help_text='GPIO pin number the wireless transmitter is attached to.', unique=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AlterField(
            model_name='pollinterval',
            name='value',
            field=models.IntegerField(choices=[(2, '2 minutes'), (5, '5 minutes'), (10, '10 minutes'), (15, '15 minutes'), (30, '30 minutes')], default=5, help_text='How frequently sensors will be polled.', unique=True),
        ),
    ]
