# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 16:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outlet', '0002_auto_20170906_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hour', models.IntegerField(default=0, help_text='Hour to turn ON (0 to 23)', validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(23)])),
                ('on_min', models.IntegerField(default=0, help_text='Minute to turn ON (0 to 59)', validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(59)])),
                ('off_hour', models.IntegerField(default=0, help_text='Hour to turn OFF  (0 to 23)', validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(23)])),
                ('off_min', models.IntegerField(default=0, help_text='Minute to turn OFF  (0 to 59)', validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(59)])),
                ('days', models.IntegerField(default=0, help_text='Days to run. Binary encoded')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.Outlet')),
            ],
        ),
    ]
