# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='off_hour',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='off_min',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='on_hour',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='on_min',
        ),
        migrations.AddField(
            model_name='schedule',
            name='off_time',
            field=models.TextField(default='7:00 PM', help_text='OFF time. Like "12:00 PM"'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='on_time',
            field=models.TextField(default='7:00 AM', help_text='ON time. Like "7:30 AM"'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='days',
            field=models.IntegerField(default=127, help_text='Days to run. Binary encoded'),
        ),
    ]
