# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 20:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sensor 1', help_text='Name of this outlet. Must be unique. 24 characters', max_length=24, unique=True)),
                ('channel', models.IntegerField(default=1, help_text='Channel number', unique=True, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)])),
                ('state', models.BooleanField(default=False, help_text='Device state. On(True) or Off(False)')),
            ],
        ),
    ]
