# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 16:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='channel',
            field=models.IntegerField(default=1, help_text='Channel number', unique=True, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='name',
            field=models.CharField(help_text='Name of this outlet. Must be unique. 24 characters', max_length=24, unique=True),
        ),
    ]
